# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Sanskar Bhushan <sbdtu5498@gmail.com>

apiVersion: batch/v1
kind: Job
metadata:
  name: github-cloning-job
spec:
  template:
    spec:
      containers:
        - name: github-cloning-container
          image: alpine/git
          command: ["git", "clone", "https://github.com/kernelci/kernelci-api.git", "/home/kernelci-api"]
          volumeMounts:
            - name: github-repo
              mountPath: /home/kernelci-api
      restartPolicy: Never
      volumes:
        - name: github-repo
          hostPath:
            path: /home/docker/kernelci-api
            type: DirectoryOrCreate
  backoffLimit: 1
