---
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: kernelci-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kernelci/api
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command:
            - uvicorn
          args:
            - api.main:versioned_app
            - --port
            - '8000'
            - --host
            - 0.0.0.0
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: kernelci-api-secret
                  key: secret-key
            - name: EMAIL_SENDER
              valueFrom:
                configMapKeyRef:
                  name: kernelci-api-config
                  key: email_sender
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kernelci-api-secret
                  key: email-password
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: kernelci-api-config
                  key: smtp_host
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: kernelci-api-config
                  key: smtp_port
            - name: MONGO_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: kernelci-api-config
                  key: mongo_service
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: kernelci-api-config
                  key: redis_host
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: kernelci-api
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: api
