---
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: kernelci-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          resources:
            requests:
              memory: "10Gi"
              cpu: "2"
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-persistent-storage-claim2
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: kernelci-api
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: mongo-persistent-storage-claim2
  namespace: kernelci-api
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: managed-csi-premium
  volumeMode: Filesystem
  volumeName: pvc-254329bd-3d3c-4601-a3f6-c8733db3aab5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  finalizers:
  - external-provisioner.volume.kubernetes.io/finalizer
  - kubernetes.io/pv-protection
  - external-attacher/disk-csi-azure-com
  name: pvc-254329bd-3d3c-4601-a3f6-c8733db3aab5
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongo-persistent-storage-claim2
    namespace: kernelci-api
  csi:
    driver: disk.csi.azure.com
    volumeAttributes:
      csi.storage.k8s.io/pv/name: pvc-254329bd-3d3c-4601-a3f6-c8733db3aab5
      csi.storage.k8s.io/pvc/name: mongo-persistent-storage-claim2
      csi.storage.k8s.io/pvc/namespace: kernelci-api
      skuname: Premium_LRS
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi-premium
  volumeMode: Filesystem
