#!/usr/bin/env python3
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Collabora Limited
# Author: Jeny Sadadia <jeny.sadadia@collabora.com>

"""Command line utility for creating default groups"""

import subprocess


DEFAULT_GROUPS = ['admin']

def create_group(group_name):
    """
    Create user group
    """
    cmd = f"docker-compose exec db /bin/mongo kernelci --eval \
\"db.usergroup.insert({{name: '{group_name}'}})\""
    ret_code = subprocess.call(cmd, shell=True)
    return ret_code == 0


def main():
    for group in DEFAULT_GROUPS:
        if not create_group(group):
            print(f"Failed to execute command for adding group: {group}")

if __name__ == "__main__":
    main()
