# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 Sanskar Bhushan <sbdtu5498@gmail.com>

apiVersion: v1
kind: Service
metadata:
  name: kernelci-api
spec:
  selector:
    app: kernelci-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: ClusterIP
