# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 KernelCI Authors.
# Author: Sanskar Bhushan <sbdtu5498@gmail.com>

apiVersion: v1
kind: Service
metadata:
  name: kernelci-api-db
spec:
  selector:
    app: kernelci-api-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
