# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 KernelCI Authors.
# Author: Sanskar Bhushan <sbdtu5498@gmail.com>

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
spec:
  # HostPath is only for single node testing only.
  # For multi node testing local volume can be used.
  # Need to create a storage class for local volume and test it on multi node cluster.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
