# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2023 KernelCI Authors.
# Author: Sanskar Bhushan <sbdtu5498@gmail.com>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernelci-api-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernelci-api-redis
  template:
    metadata:
      labels:
        app: kernelci-api-redis
    spec:
      containers:
        - name: kernelci-api-redis
          image: redis:6.2
          volumeMounts:
            - name: redis-data
              mountPath: /data
          # Resource limits needs to be discussed.
          resources:
          ports:
            - containerPort: 6379  # Expose Redis standard port
      volumes:
        - name: redis-data
          hostPath:
            path: /home/docker/kernelci-api/redis/data
